environment:
  access_token:
    secure: qNMRA5boyCslJ9JgiqjpLdHd0NvhQVWcjJx3ZMrcgrDz6DNFJnDsV7w9IZuhqwYZ

build_script:
 - git config --global credential.helper store
 - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
 - git config --global user.email "appveyor@notarealem.ail"
 - git config --global user.name "Appveyor Automated Build"
 - cmd: For /f "tokens=2-4 delims=/ " %%a in ('date /t') do (set mydate=%%c-%%a-%%b)
 - cmd: For /f "tokens=1-2 delims=/:" %%a in ('time /t') do (set mytime=%%a:%%b)
 #
 - git checkout master
 - ps: |-
    #
    $ErrorActionPreference = 'SilentlyContinue'
    
    curl.exe -L https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win32.exe --output jq.exe
  
    $apk = $(curl.exe -s https://api.github.com/repos/bromite/bromite/releases/latest 2> $null | ./jq.exe -r '.assets[] | {url: .browser_download_url, name: .name} | select(.name == \"arm64_SystemWebView.apk\") | .url')
    mkdir system/app/webview -ea 0
    curl.exe -L $apk --output system/app/webview/webview.apk 2> $null
    
    git add system/app/webview/webview.apk
    git commit -m "Automated Appveyor build at $env:mydate, $env:mytime [skip ci]" --amend --allow-empty
    git push -f origin master
    
    $LASTEXITCODE = 0
    exit
    #

artifacts:
  - path: .
    type: zip

deploy:
  - provider: NuGet
    skip_symbols: false
    api_key:
      secure: A8JdC8M46tJ0WR+LjRq2cHuMfjCOEZ2xU7c75iayd7AnNvgqq7XrCKV5uGyeTpZL
    # don't push D#+ packages, also don't push test packages
    artifact: /.*/
   
